name             'chef-3scale'
maintainer       '3scale Inc.'
maintainer_email 'support@3scale.net'
license          'All rights reserved'
description      'Installs/Configures chef-3scale'
long_description 'Installs/Configures chef-3scale'
version          '0.1.0'
