name             'chef-3scale'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures chef-3scale'
long_description 'Installs/Configures chef-3scale'
version          '0.1.0'
